import type { Estimate, ISODate } from "../types";

/**
 * The team's sprint sheet (Aug 28 – Sep 24, plus work started for the next
 * sprint), transcribed as sample data. Titles are lightly cleaned (typos,
 * very long text moved into notes); dates, owners, estimates and statuses are
 * as recorded in the sheet.
 *
 * Adjustments, listed in HANDOFF.md:
 * - "Goal" cells that were really task names are grouped under a matching goal.
 * - Rows with no start date use the start of their sprint; rows with no estimate use 1 day.
 * - The duplicated "vibration stability" task is kept once, in the later sprint.
 * - Rows with no owner, the empty Rupam row, and a claude.ai share link (it carries a private key) are left out.
 * - The duplicated "false device alert from the watchdog" task is kept once.
 * - Rows with no status are treated as Not Started.
 * - A done date after the demo's today (25 Sep) is shown as still in progress.
 */

export type GoalKey =
  | "release"
  | "revamp"
  | "infra"
  | "current"
  | "bowl"
  | "vkgs"
  | "books"
  | "sam"
  | "foodwater"
  | "station"
  | "jigs"
  | "strength"
  | "tracker"
  | "components"
  | "som"
  | "wifi"
  | "website"
  | "breed"
  | "observability"
  | "posthog"
  | "hcam"
  | "pipeline"
  | "doghouse";

export const SHEET_GOALS: Record<GoalKey, { title: string; createdBy: string; notes?: string }> = {
  release: { title: "New app release stabilisation and monitoring", createdBy: "p-kunal" },
  revamp: { title: "New App Revamp", createdBy: "p-abhinav" },
  infra: { title: "Infrastructure & backend changes", createdBy: "p-rupam" },
  current: { title: "Current app stabilisation and weekly release", createdBy: "p-kunal" },
  bowl: { title: "Make EverBowl reliable: zero functional issues, complete and consistent data capture", createdBy: "p-rupam" },
  vkgs: { title: "EverWiz integration with vkgs", createdBy: "p-surya" },
  books: { title: "Start 500-book ingestion on the credit account", createdBy: "p-surya" },
  sam: { title: "1500 labelled audios for noise cancellation using SAM audio", createdBy: "p-surya" },
  foodwater: { title: "Food and water detection model training and validation", createdBy: "p-surya" },
  station: { title: "EverBowl production station: operator tool", createdBy: "p-vaishak" },
  jigs: { title: "Production jigs: preparation, manufacturing and testing", createdBy: "p-vasanth" },
  strength: { title: "EverBowl strength and structure validation", createdBy: "p-vasanth" },
  tracker: { title: "Tracker and Hub: engineering modelling, setup and battery", createdBy: "p-vasanth" },
  components: { title: "EverBowl components", createdBy: "p-vasanth" },
  som: { title: "AM62A7 SOM Rev1.1 schematic and carrier PCB", createdBy: "p-vinayak" },
  wifi: { title: "Bowl carrier PCB update: Wi-Fi dongle finalisation", createdBy: "p-vinayak" },
  website: { title: "Primary website: SEO, content and conversion", createdBy: "p-shreya" },
  breed: { title: "Pet breed detection accuracy", createdBy: "p-aarthi" },
  observability: { title: "EverBowl observability in Doghouse", createdBy: "p-vaishak" },
  posthog: { title: "PostHog analytics for the revamp app", createdBy: "p-shreya" },
  hcam: { title: "HCAM2N6 evaluation board bring-up", createdBy: "p-vaishak" },
  pipeline: { title: "Release pipeline setup", createdBy: "p-vaishak" },
  doghouse: { title: "Doghouse API migration to the new production server", createdBy: "p-kunal" },
};

/** Sprint as labelled in the sheet ("Sep 21 – Oct 2" overlapped Sep 11 – 24 and is treated as the next fortnight). */
export type SheetSprint = "aug28" | "sep11" | "sep21";

export interface SheetRow {
  sprint: SheetSprint;
  owner: string;
  goal: GoalKey;
  title: string;
  notes?: string;
  /** "Support" column, when it names someone other than the owner. */
  support?: string;
  est: Estimate;
  status: "done" | "in_progress" | "blocked" | "not_started";
  start?: ISODate;
  done?: ISODate;
  /** Result / Notes column shown on the day the task was done. */
  result?: string;
  /** Who the owner is waiting on, and for what. */
  dep?: { personId: string; description: string };
  links?: { label: string; url: string }[];
}

export const SHEET_ROWS: SheetRow[] = [
  // ── Aug 28 – Sep 10 ──
  { sprint: "aug28", owner: "p-abhinav", goal: "release", title: "Test the pet tag, quiz, pulse and profile screens", est: 1.5, status: "done", start: "2026-08-31", done: "2026-08-31" },
  { sprint: "aug28", owner: "p-abhinav", goal: "release", title: "Set up Jenkins and observability", est: 1.5, status: "done", start: "2026-08-31", done: "2026-09-01" },
  { sprint: "aug28", owner: "p-abhinav", goal: "release", title: "Fix the bugs reported in design", est: 1, status: "done", start: "2026-09-01", done: "2026-09-01" },
  { sprint: "aug28", owner: "p-abhinav", goal: "release", title: "Complete the UI for the community", est: 0.5, status: "done", start: "2026-09-01", done: "2026-09-01" },
  { sprint: "aug28", owner: "p-kunal", goal: "infra", title: "Set up Amazon SES for the new app's production environment", notes: "Enables reliable transactional email delivery.", est: 1, status: "done", start: "2026-08-31", done: "2026-09-01" },
  { sprint: "aug28", owner: "p-kunal", goal: "release", title: "Incorporate all changes and enhancements recommended by the Product team", est: 2, status: "done", start: "2026-09-02", done: "2026-09-07" },
  { sprint: "aug28", owner: "p-kunal", goal: "release", title: "Fix UI and functional bugs reported by the team for a smooth app experience", est: 1, status: "done", start: "2026-09-03", done: "2026-09-07" },
  { sprint: "aug28", owner: "p-kunal", goal: "current", title: "RCA: owner name showing as “User” on Shopify for pet tag orders", notes: "Reported by Balram.", est: 0.5, status: "done", start: "2026-09-03", done: "2026-09-03" },
  {
    sprint: "aug28",
    owner: "p-kunal",
    goal: "current",
    title: "Change the delivery charges for pet tag orders for US and Indian users",
    notes: "Pranjal will provide the new price details and business requirements for the pet tag.",
    est: 1,
    status: "blocked",
    start: "2026-09-07",
    dep: { personId: "p-pranjal", description: "New price details and business requirements for the pet tag" },
  },
  { sprint: "aug28", owner: "p-kunal", goal: "current", title: "Generate the QR code for a pet tag once it's ordered", est: 1, status: "done", start: "2026-09-07", done: "2026-09-08" },
  { sprint: "aug28", owner: "p-kunal", goal: "release", title: "Fix the OpenSearch deployment and text search in the Community module", est: 1, status: "done", start: "2026-09-04", done: "2026-09-07" },
  { sprint: "aug28", owner: "p-kunal", goal: "infra", title: "Migrate existing user and device data to the new schema with zero data loss", notes: "Includes fixing app defects the migration surfaces.", est: 2, status: "not_started" },
  { sprint: "aug28", owner: "p-kunal", goal: "infra", title: "Set up the App Store and Google Play configuration for the new app release", est: 1, status: "done", start: "2026-09-09", done: "2026-09-18" },
  { sprint: "aug28", owner: "p-rupam", goal: "infra", title: "Dev environment migrated and verified (Waves 1–2 + S3 user content)", est: 1.5, status: "done", start: "2026-08-28", done: "2026-08-31" },
  { sprint: "aug28", owner: "p-rupam", goal: "infra", title: "Finish the Wave 3 proof and run the S3 URL backfill", est: 2, status: "done", start: "2026-09-01", done: "2026-09-03" },
  { sprint: "aug28", owner: "p-rupam", goal: "infra", title: "Close the open calls the dev rehearsal surfaced", est: 1, status: "not_started" },
  { sprint: "aug28", owner: "p-rupam", goal: "infra", title: "Migrate the community from document storage", est: 2, status: "done", start: "2026-09-02", done: "2026-09-08" },
  { sprint: "aug28", owner: "p-rupam", goal: "infra", title: "KeySpace DB migration", est: 1.5, status: "done", start: "2026-09-07", done: "2026-09-09" },
  { sprint: "aug28", owner: "p-rupam", goal: "infra", title: "Production infrastructure setup", est: 2, status: "done", start: "2026-09-09", done: "2026-09-11" },
  { sprint: "aug28", owner: "p-shreya", goal: "release", title: "Identify API performance and response-time issues under load", est: 1, status: "done", result: "Load-testing data in api-loadtesting-data.doc." },
  { sprint: "aug28", owner: "p-surya", goal: "vkgs", title: "Make ingestion more robust: recover from timeouts and autoscale machines by usage", est: 1, status: "done", start: "2026-08-31", done: "2026-09-10" },
  { sprint: "aug28", owner: "p-surya", goal: "sam", title: "Dashboard for verifying audios labelled by the SAM audio model", est: 1, status: "done", start: "2026-08-31", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-surya", goal: "revamp", title: "Add a guardrail to the new app and test it", est: 0.5, status: "done", start: "2026-09-01", done: "2026-09-15" },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "bowl",
    title: "Bowl 460: fix SOM2 data loss; bowl 441: load cell weight calibration",
    notes: "1. Bowl 460: debug and fix SOM2 data loss\n2. Bowl 441: load cell weight calibration",
    support: "p-vasanth",
    est: 1,
    status: "done",
    start: "2026-08-31",
    done: "2026-08-31",
  },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "station",
    title: "CM4 flashing: one-click image flash with safety rails",
    notes: "rpiboot → eMMC detection by USB descriptor → zero/dd/verify engine with safety rails; the operator flashes a CM4 image with one click.",
    est: 0.5,
    status: "done",
    start: "2026-09-01",
    done: "2026-09-01",
  },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "station",
    title: "SOM flashing: one-click SOM1/SOM2 flash",
    notes: "STM32 DFU engine (recovery stub + boot-status blank + app in one session, dfu-util with CubeProgrammer fallback).",
    est: 0.5,
    status: "done",
    start: "2026-09-02",
    done: "2026-09-02",
  },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "station",
    title: "Proximity calibration: remote VL53L1X calibration driver",
    notes: "Guided jig prompts, result gates, live-distance verification window, one-shot lockout.",
    support: "p-vasanth",
    est: 1,
    status: "done",
    start: "2026-09-03",
    done: "2026-09-03",
  },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "station",
    title: "Weight calibration: on-device helper and guided flow",
    notes: "weight_calibrate helper (tare + reference mass → simple_calibration.dat) and a guided tool flow with a post-calibration accuracy check.",
    support: "p-vasanth",
    est: 1,
    status: "done",
    start: "2026-09-04",
    done: "2026-09-04",
  },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "station",
    title: "Operator GUI: diagnostics and report",
    notes: "18-check device checklist (sensors, services, CAN, network, end-to-end capture) and a branded JSON + HTML report per device.",
    est: 2,
    status: "done",
    start: "2026-09-07",
    done: "2026-09-08",
  },
  { sprint: "aug28", owner: "p-vaishak", goal: "wifi", title: "Test Wi-Fi/BLE dongles from different manufacturers for the new carrier PCB", est: 1, status: "done", start: "2026-09-01", done: "2026-09-01" },
  { sprint: "aug28", owner: "p-vasanth", goal: "strength", title: "Drop test: simulation, calculations and report", est: 1, status: "done", start: "2026-08-31", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-vasanth", goal: "tracker", title: "ID sketches", est: 2, status: "done", start: "2026-09-02", done: "2026-09-07" },
  { sprint: "aug28", owner: "p-vasanth", goal: "jigs", title: "SOM1 jig: proximity calibration", support: "p-vaishak", est: 2, status: "done", start: "2026-09-15", done: "2026-09-21" },
  { sprint: "aug28", owner: "p-vasanth", goal: "jigs", title: "SOM1 camera module jig", support: "p-vaishak", est: 2, status: "done", start: "2026-09-15", done: "2026-09-21" },
  { sprint: "aug28", owner: "p-vinayak", goal: "som", title: "Schematic modification: verification review", notes: "Reviewed with a freelancer.", est: 2, status: "done", start: "2026-08-31", done: "2026-09-01" },
  { sprint: "aug28", owner: "p-vinayak", goal: "som", title: "Schematic completion with PCB footprint verification", est: 2, status: "done", start: "2026-09-15", done: "2026-09-16" },
  { sprint: "aug28", owner: "p-vinayak", goal: "wifi", title: "Finalise the Wi-Fi dongle PCB footprint from the test results", est: 1, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-shreya", goal: "website", title: "Remove unused and old URLs from the primary website", est: 0.5, status: "done", start: "2026-08-31", done: "2026-08-31" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "EverBowl flow and all Community UI screens", est: 1.5, status: "done", start: "2026-08-31", done: "2026-09-21" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Fix the reported bug list (UI and logic)", est: 2, status: "done", start: "2026-09-01", done: "2026-09-03" },
  { sprint: "aug28", owner: "p-shreya", goal: "website", title: "Implement the new EverBowl order-confirmation page design", est: 1, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Bottom sheet design on the home screen", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "SOS QR code generation", notes: "QR generation logic was missing and the QR wasn't shown.", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-17" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Your pets → vault flow: completion % should increase", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Profile section icons: placement, sizing and design as per Figma", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Implement delete account, including all of the user's data", est: 1, status: "done", start: "2026-09-02", done: "2026-09-17" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Fix home screen spacing as per the designs", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Make “Your pets” clickable: go to the pet vault and increase %", est: 0.5, status: "done", start: "2026-09-01", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Implement edit functionality", est: 0.5, status: "done", start: "2026-09-01", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "SOS UI as per Figma (reddish gradient)", est: 0.5, status: "done", start: "2026-09-01", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-vaishak", goal: "strength", title: "One ADC firmware: two load cells on one ADC for mechanical testing", est: 1, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "EverBowl screens: UI changes to match the new designs", est: 1, status: "done", start: "2026-09-03", done: "2026-09-04" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Fix the bug list", est: 0.5, status: "done", start: "2026-09-07", done: "2026-09-08" },
  {
    sprint: "aug28",
    owner: "p-aarthi",
    goal: "revamp",
    title: "Onboarding flow fixed end to end",
    notes: "Profile photo from the Google account; profile name from Google or Apple, falling back to asking “What can we call you”; breed selection corrected.",
    est: 0.5,
    status: "done",
    start: "2026-09-02",
    done: "2026-09-03",
  },
  { sprint: "aug28", owner: "p-vaishak", goal: "tracker", title: "Hub and tracker setup for Rana's activity-tracking data collection", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-shreya", goal: "revamp", title: "Understand OpenSearch and why it helps Community", est: 0.5, status: "done", start: "2026-09-02", done: "2026-09-02" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Wi-Fi screens (rename EverBowl on the backend)", est: 1, status: "done", start: "2026-09-03", done: "2026-09-03" },
  {
    sprint: "aug28",
    owner: "p-shreya",
    goal: "website",
    title: "Unique SEO meta title, description and category for every blog post",
    notes: "All posts have titles under 60 characters, descriptions of 110–155 characters, and are mapped to the right category hub.",
    est: 0.5,
    status: "done",
    start: "2026-09-07",
    done: "2026-09-07",
  },
  {
    sprint: "aug28",
    owner: "p-shreya",
    goal: "website",
    title: "Set the correct indexing status for tag pages",
    notes: "23 tags indexed with unique descriptions, 76 duplicates merged or redirecting, no thin pages in the index.",
    est: 1,
    status: "done",
    start: "2026-09-07",
    done: "2026-09-07",
  },
  { sprint: "aug28", owner: "p-pritam", goal: "revamp", title: "Web view screen after scanning the code", est: 0.5, status: "done", start: "2026-09-08", done: "2026-09-17" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Pet tag flow: order placed screen and zero-value coupon order flow", est: 0.5, status: "done", start: "2026-09-07", done: "2026-09-07" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "SOS takeover flow", est: 0.5, status: "done", start: "2026-09-07", done: "2026-09-07" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Make profile and photo edits instant in the UI", est: 0.5, status: "done", start: "2026-09-07", done: "2026-09-07" },
  {
    sprint: "aug28",
    owner: "p-aarthi",
    goal: "revamp",
    title: "SOS reliability fixes and architecture cleanup",
    notes: "SOS restores on cold start (reopening during a live alert lands on SOS, not home). The emergency screen no longer goes blank on re-entry, and returning to the poster or vet chat redraws the stored conversation.",
    est: 0.5,
    status: "done",
    start: "2026-09-08",
    done: "2026-09-09",
  },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "SOS: two CTAs after one minute; edit details and pet image before sharing the poster", est: 0.5, status: "done", start: "2026-09-08", done: "2026-09-09" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Community comments section UI", est: 0.5, status: "done", start: "2026-09-08", done: "2026-09-09" },
  {
    sprint: "aug28",
    owner: "p-vaishak",
    goal: "bowl",
    title: "Build and verify everOS 2.0.0 from the clean git tree with all reliability fixes",
    notes: "CM4 image built green and content-verified from the clean scarthgap tree; 8 latent build gaps fixed and committed.",
    est: 2,
    status: "done",
    start: "2026-09-08",
    done: "2026-09-10",
  },
  { sprint: "aug28", owner: "p-vinayak", goal: "som", title: "Final review of the modified AM62A7 schematic", notes: "Design completed on 8 Sep.", est: 2, status: "done", start: "2026-09-08", done: "2026-09-10" },
  { sprint: "aug28", owner: "p-vinayak", goal: "wifi", title: "Complete the PCB layout with the new dongle connector", est: 2, status: "done", start: "2026-09-07", done: "2026-09-08" },
  { sprint: "aug28", owner: "p-shreya", goal: "observability", title: "Improve device-offline Slack alerts", notes: "Understanding the flow to add intelligence to device-offline alerts.", est: 1.5, status: "in_progress", start: "2026-09-08" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "Journal UI fixes: icon colours, sizes, spacing and bottom sheet", est: 0.5, status: "done", start: "2026-09-08", done: "2026-09-09" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "New designs: Community crop, toasters, pet vault edit screen", est: 0.5, status: "done", start: "2026-09-09", done: "2026-09-10" },
  {
    sprint: "aug28",
    owner: "p-aarthi",
    goal: "revamp",
    title: "New high and medium bug list across the app",
    notes: "EverWiz, Pet Vault, Journal, EverBowl, Community, Navigation and Paw Pulse.",
    est: 1,
    status: "done",
    start: "2026-09-10",
    done: "2026-09-11",
  },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Fix the 209 bugs", est: 1, status: "done", start: "2026-09-08", done: "2026-09-09" },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Add the profiler to the app", est: 1, status: "done", start: "2026-09-08", done: "2026-09-16" },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Complete the permission screen", est: 1, status: "done", start: "2026-09-08", done: "2026-09-09" },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Fix the bugs reported for profile and notifications", est: 1, status: "done", start: "2026-09-09", done: "2026-09-10" },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Verify analytics and observability tools (PostHog, UXCam, Firebase Crashlytics)", est: 1, status: "done", start: "2026-09-10", done: "2026-09-11" },
  { sprint: "aug28", owner: "p-aarthi", goal: "revamp", title: "New designs: tooltips, pet vault docs card, email flow, delete pet", est: 1, status: "done", start: "2026-09-10", done: "2026-09-11" },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Complete the deeplink engine", est: 1, status: "done", start: "2026-09-10", done: "2026-09-11" },
  { sprint: "aug28", owner: "p-abhinav", goal: "revamp", title: "Fix the issues reported on profile and notifications", est: 0.5, status: "done", start: "2026-09-10", done: "2026-09-11" },

  // ── Sep 11 – Sep 24 ──
  { sprint: "sep11", owner: "p-rupam", goal: "infra", title: "Migration and routing setup from Account A to Account B", est: 2, status: "done", start: "2026-09-15", done: "2026-09-19" },
  { sprint: "sep11", owner: "p-rupam", goal: "bowl", title: "Deep dive and break the functionality to understand patterns and behaviour", est: 2, status: "done", start: "2026-09-15", done: "2026-09-17" },
  { sprint: "sep11", owner: "p-rupam", goal: "infra", title: "Set up S3 for the new backend with migrated data, easy to fetch", est: 1, status: "done", start: "2026-09-18", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-rupam", goal: "infra", title: "Production: data migration to the production database", est: 1, status: "done", start: "2026-09-18", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-rupam", goal: "infra", title: "Production: community migration to the production database", est: 1, status: "done", start: "2026-09-18", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-surya", goal: "vkgs", title: "Backfill user context and device data in vkgs for retrieval (10 users)", est: 2, status: "done", start: "2026-09-01", done: "2026-09-21" },
  { sprint: "sep11", owner: "p-surya", goal: "books", title: "Ingestion and retrieval active on 500 books", est: 1, status: "done", start: "2026-09-15", done: "2026-09-21" },
  { sprint: "sep11", owner: "p-surya", goal: "bowl", title: "Bowl removed should not show up as consumption", est: 0.5, status: "done", start: "2026-09-17", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-surya", goal: "bowl", title: "Root cause and fix feeding events not being visible", est: 0.5, status: "done", start: "2026-09-20", done: "2026-09-21" },
  { sprint: "sep11", owner: "p-vasanth", goal: "tracker", title: "CAD modelling", est: 2, status: "in_progress", start: "2026-09-17" },
  { sprint: "sep11", owner: "p-vasanth", goal: "components", title: "Steel bowls: modelling", est: 0.5, status: "done", start: "2026-09-18", done: "2026-09-18" },
  {
    sprint: "sep11",
    owner: "p-vaishak",
    goal: "tracker",
    title: "Tracker battery: power consumption calculation and 24 h soak with a 500 mAh battery",
    notes: "Battery simulation and power consumption calculation with a 500 mAh battery; end-to-end validation with a 24 h tracker↔hub soak on the new builds and a first real battery number.",
    est: 2,
    status: "not_started",
  },
  { sprint: "sep11", owner: "p-vaishak", goal: "observability", title: "Complete observability of bowl detection and ML model events on the dashboard", support: "p-pritam", est: 2, status: "done", start: "2026-09-15", done: "2026-09-17" },
  { sprint: "sep11", owner: "p-kunal", goal: "release", title: "New production server setup", est: 1, status: "done", start: "2026-09-11", done: "2026-09-11" },
  { sprint: "sep11", owner: "p-kunal", goal: "release", title: "Migrate legacy EverBowl endpoints", est: 1, status: "done", start: "2026-09-11", done: "2026-09-18" },
  {
    sprint: "sep11",
    owner: "p-kunal",
    goal: "release",
    title: "Move the Doghouse pet tag order flow to the new production APIs",
    notes: "Migrate the existing integration from the old backend APIs to the new production backend.",
    est: 1,
    status: "done",
    start: "2026-09-21",
    done: "2026-09-22",
  },
  { sprint: "sep11", owner: "p-vinayak", goal: "som", title: "Schematic modification for the AM62A7 SOM carrier PCB", est: 2, status: "done", start: "2026-09-16", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-abhinav", goal: "revamp", title: "Complete app testing", est: 1, status: "done", start: "2026-09-11", done: "2026-09-16" },
  { sprint: "sep11", owner: "p-aarthi", goal: "revamp", title: "All new design changes, pet vault bug fixes and app testing", est: 1, status: "done", start: "2026-09-10", done: "2026-09-11" },
  {
    sprint: "sep11",
    owner: "p-aarthi",
    goal: "revamp",
    title: "Force update screen and EverBowl connection check",
    notes: "Verified force update; tested the EverBowl connection process updating DynamoDB in the old account as expected.",
    est: 0.5,
    status: "done",
    start: "2026-09-15",
    done: "2026-09-15",
  },
  {
    sprint: "sep11",
    owner: "p-aarthi",
    goal: "revamp",
    title: "SOS exit screens and incident race-condition fix",
    notes: "Race condition in SosService.raise_incident; pet vault profile text and bowl text changes suggested by Tanya.",
    est: 0.5,
    status: "done",
    start: "2026-09-15",
    done: "2026-09-15",
  },
  { sprint: "sep11", owner: "p-abhinav", goal: "revamp", title: "Learn MQTT and plan the next actions", est: 1, status: "done", start: "2026-09-15", done: "2026-09-16" },
  { sprint: "sep11", owner: "p-abhinav", goal: "revamp", title: "Pet tag, prompts and community on Doghouse", est: 2, status: "done", start: "2026-09-16", done: "2026-09-22" },
  { sprint: "sep11", owner: "p-abhinav", goal: "revamp", title: "Create thumbnail images for migrated data", est: 1, status: "done", start: "2026-09-16", done: "2026-09-23" },
  { sprint: "sep11", owner: "p-abhinav", goal: "revamp", title: "Create journals for migrated users", est: 1, status: "done", start: "2026-09-18", done: "2026-09-22" },
  { sprint: "sep11", owner: "p-shreya", goal: "website", title: "New non-technical blog content for the website", est: 0.5, status: "done", start: "2026-09-16", done: "2026-09-16" },
  { sprint: "sep11", owner: "p-shreya", goal: "website", title: "CRO and CTA updates for the SEO audit", est: 0.5, status: "done", start: "2026-09-16", done: "2026-09-16" },
  {
    sprint: "sep11",
    owner: "p-aarthi",
    goal: "breed",
    title: "Measure breed detection accuracy on the Stanford and Hoomanely datasets",
    notes: "Stanford dataset: 90.7% accuracy. Done for the Hoomanely dataset; collecting top-10 breed images to measure accuracy on the new dataset.",
    est: 1,
    status: "done",
    start: "2026-09-16",
    done: "2026-09-17",
    links: [
      { label: "Breed accuracy notes", url: "https://docs.google.com/document/d/1apD1gaPcKrAucr_jYHYqTjJ3UQV97jjD0mKqi9OvFWA/edit?tab=t.py6wgv2k34pd" },
      { label: "Top-10 breed accuracy (Kaggle)", url: "https://www.kaggle.com/code/aarthihonguthi/top-10-breed-accuracy" },
    ],
  },
  { sprint: "sep11", owner: "p-vaishak", goal: "bowl", title: "Fix temperature event generation and verify events are recorded", est: 1, status: "done", start: "2026-09-17", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-vaishak", goal: "bowl", title: "Fix audio classification event generation and verify events are recorded", est: 1, status: "done", start: "2026-09-18", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-vaishak", goal: "bowl", title: "Enable the SOM2 camera IR LED during capture for clearer low-light images", est: 2, status: "done", start: "2026-09-23", done: "2026-09-23" },
  { sprint: "sep11", owner: "p-pritam", goal: "observability", title: "Doghouse diagnostics page: new fields and CM4 data UI", est: 1, status: "done", start: "2026-09-17", done: "2026-09-22" },

  // ── "Sep 21 – Oct 2" in the sheet ──
  { sprint: "sep21", owner: "p-surya", goal: "vkgs", title: "Argos graph changes for hybrid search over the user graph, book graph and vkgs time-series DB", est: 2, status: "in_progress", start: "2026-09-21" },
  { sprint: "sep21", owner: "p-surya", goal: "vkgs", title: "Context enrichment over time in chat", est: 2, status: "in_progress", start: "2026-09-21" },
  { sprint: "sep21", owner: "p-surya", goal: "foodwater", title: "Train the model and validate against ArUco marker detection failure cases", est: 1.5, status: "in_progress", start: "2026-09-18" },
  { sprint: "sep21", owner: "p-surya", goal: "revamp", title: "Fix incorrectly parsed follow-up questions showing in the new app", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-vasanth", goal: "components", title: "Test the new steel bowl model", est: 1, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-vasanth", goal: "strength", title: "Vibration stability: simulation, calculations and report", est: 2, status: "not_started" },
  { sprint: "sep21", owner: "p-vasanth", goal: "tracker", title: "CAD modelling concepts (5–10 in total)", est: 2, status: "in_progress", start: "2026-09-21" },
  { sprint: "sep21", owner: "p-vasanth", goal: "jigs", title: "First set of jig testing", est: 1, status: "in_progress", start: "2026-09-21" },

  // ── Added later: Sep 11 – Sep 24 ──
  { sprint: "sep11", owner: "p-abhinav", goal: "revamp", title: "Update the email for OTP sign-in", est: 0.5, status: "done", start: "2026-09-17", done: "2026-09-21" },
  { sprint: "sep11", owner: "p-vaishak", goal: "bowl", title: "Remove the false device alert triggered by the watchdog", est: 1, status: "done", start: "2026-09-18", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-vaishak", goal: "bowl", title: "Fix the SOM2 audio capture failure", est: 1, status: "done", start: "2026-09-18", done: "2026-09-18" },
  {
    sprint: "sep11",
    owner: "p-aarthi",
    goal: "revamp",
    title: "SOS UI screens corrected as per the email",
    notes: "Delete account button removed, SOS text changes, 5 options added in Health Emergency, “0 scans so far” removed.",
    est: 0.5,
    status: "done",
    start: "2026-09-17",
    done: "2026-09-17",
    links: [{ label: "argos_flutter PR #221", url: "https://github.com/hoomanely/argos_flutter/pull/221" }],
  },
  { sprint: "sep11", owner: "p-shreya", goal: "posthog", title: "Test PostHog events in the revamp app", est: 0.5, status: "done", start: "2026-09-17", done: "2026-09-17" },
  { sprint: "sep11", owner: "p-shreya", goal: "posthog", title: "Add all missing PostHog events for the revamp app", notes: "Screen and ui_tap events firing correctly.", est: 0.5, status: "not_started" },
  { sprint: "sep11", owner: "p-pritam", goal: "revamp", title: "Email OTP design for email sign-in", est: 0.5, status: "done", start: "2026-09-17", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-pritam", goal: "revamp", title: "Fix compliance audit issues (3 blockers, 8 high)", notes: "From the audit doc shared by Abhinav.", est: 0.5, status: "done", start: "2026-09-18", done: "2026-09-22" },
  { sprint: "sep11", owner: "p-shreya", goal: "website", title: "Add 11 new non-technical blogs to the website", est: 0.5, status: "done", start: "2026-09-18", done: "2026-09-18" },
  {
    sprint: "sep11",
    owner: "p-aarthi",
    goal: "revamp",
    title: "Pet tag flow test",
    notes: "Pet tag → QR (wrong QR error) → CTA not wired → Activate Pet Tag has no entry point → notifications after scan work → website not deployed (works on localhost).",
    est: 1,
    status: "done",
    start: "2026-09-18",
    done: "2026-09-18",
  },
  { sprint: "sep11", owner: "p-aarthi", goal: "revamp", title: "Verify 5 old-app users' data against the database", notes: "Results updated in the sheet.", est: 0.5, status: "done", start: "2026-09-18", done: "2026-09-18" },
  { sprint: "sep11", owner: "p-vaishak", goal: "bowl", title: "Fix the SOM2 IR LED on camera capture", support: "p-vasanth", est: 1, status: "not_started" },

  // ── Added later: "Sep 21 – Oct 2" ──
  { sprint: "sep21", owner: "p-vinayak", goal: "som", title: "Schematic modification for the AM62A7 SOM pinout and related circuits", est: 2, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-vinayak", goal: "som", title: "PCB layout modification for AM62A7 SOM compatibility", notes: "Adding a few changes suggested by Vipin.", est: 2, status: "in_progress", start: "2026-09-22" },
  { sprint: "sep21", owner: "p-vinayak", goal: "som", title: "First review of the PCB layout: power, digital and analog sections", est: 2, status: "not_started", start: "2026-09-22" },
  { sprint: "sep21", owner: "p-vaishak", goal: "hcam", title: "Complete memory mapping: eMMC boot-up, external RAM and external flash", est: 2, status: "done", start: "2026-09-22", done: "2026-09-23" },
  { sprint: "sep21", owner: "p-vaishak", goal: "hcam", title: "Complete CSI camera capture: on-board JPEG compression with external flash storage", est: 1, status: "done", start: "2026-09-23", done: "2026-09-23" },
  { sprint: "sep21", owner: "p-vaishak", goal: "pipeline", title: "Complete audio mic SAI: audio capture and storage", est: 1, status: "in_progress", start: "2026-09-25" },
  { sprint: "sep21", owner: "p-vaishak", goal: "hcam", title: "Complete USB-CAN SOM-to-SOM communication", est: 1, status: "not_started" },
  { sprint: "sep21", owner: "p-vaishak", goal: "bowl", title: "Enable the SOM2 IR LED on camera capture", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-abhinav", goal: "revamp", title: "Fix backend scaling", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-abhinav", goal: "revamp", title: "Add backend alarms for observability", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Make iOS and Android releases developer-agnostic", est: 1, status: "not_started" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Bring the prompts to Doghouse", est: 0.5, status: "not_started" },
  { sprint: "sep21", owner: "p-abhinav", goal: "revamp", title: "Add impersonation to the new app", est: 1, status: "done", start: "2026-09-22", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-abhinav", goal: "revamp", title: "Fix the local database in the app", est: 1, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Change the logo on the Google sign-in page", est: 0.5, status: "done", start: "2026-09-23", done: "2026-09-23" },
  { sprint: "sep21", owner: "p-abhinav", goal: "revamp", title: "Create the app profiler and fix memory leaks", est: 1, status: "not_started" },
  { sprint: "sep21", owner: "p-abhinav", goal: "revamp", title: "Add journals for migrated users", est: 1.5, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Fix the quiz showing unanswered after logging out and back in", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Improve the “Learned by EverWiz” generation", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "SOS poster photo flow shows the correct photo on the public page", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Update the Call Owner and Share Location CTA flows", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Tooltips shown again after sign-out", notes: "New finding.", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Community: own post “…” menu differs between feed and detail", notes: "New finding.", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "EverWiz chat on a new day shows “See previous messages” instead of the past chat", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Journal “View Chat” opens full page with a close option", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Fix the SOS notification opening the previous SOS screen", est: 0.5, status: "done", start: "2026-09-20", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Remove text from the NFC QR tag", est: 0.5, status: "done", start: "2026-09-20", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Fetch Community posts by region", est: 1.5, status: "in_progress", start: "2026-09-23" },
  { sprint: "sep21", owner: "p-shreya", goal: "posthog", title: "Fire proper PostHog event names in the revamp app", notes: "Replacing ui_tap with the actual event names.", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-vaishak", goal: "bowl", title: "Move all users to the latest build (SOM + CM4) after internal testing", est: 1, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Placeholder image for pets without a photo", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Move the legacy IMU tracker feature to the new app in production and release it internally", est: 1, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Breed dropdown instead of free-text entry", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25", result: "Already implemented (discussed with Pranjal)." },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Different questions when adding a new pet, e.g. the age difference between dogs", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Two icons to reach EverWiz (toggle and chat)", notes: "It's the required design.", est: 0.5, status: "not_started" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Hoomanely logo partly over the text box looks like a glitch", notes: "Not needed (discussed with Tanya).", est: 0.5, status: "not_started" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Exiting this page navigates differently from other pages", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-22", result: "Fixed after the release (discussed with Vinayak)." },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Food and allergies update shows a dropdown of options", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "“Learned by EverWiz” summary repeats points", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-shreya", goal: "posthog", title: "Identify users in PostHog by name or email", notes: "Changing distinct_id to the user's name or email.", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-shreya", goal: "posthog", title: "Update the analytics dashboard with the revamp app's new PostHog events", est: 0.5, status: "not_started" },
  { sprint: "sep21", owner: "p-abhinav", goal: "infra", title: "Shut down previous services: close all Lambdas and crons for the current app (2.7.3)", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-22" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Scroll-to-top button", est: 0.5, status: "not_started", start: "2026-09-22" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Location selector with map support in SOS poster creation", est: 0.5, status: "done", start: "2026-09-21", done: "2026-09-21" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Tooltips shown again after logging out and back in", est: 0.5, status: "done", start: "2026-09-22", done: "2026-09-22" },
  {
    sprint: "sep21",
    owner: "p-kunal",
    goal: "doghouse",
    title: "Migrate Doghouse bulk posting, interactions and image upload APIs to the new production server",
    notes: "Complete functionality, data integrity and backward compatibility.",
    est: 1,
    status: "done",
    start: "2026-09-22",
    done: "2026-09-22",
  },
  { sprint: "sep21", owner: "p-vasanth", goal: "components", title: "EverBowl components", est: 2, status: "in_progress", start: "2026-09-22" },
  { sprint: "sep21", owner: "p-surya", goal: "revamp", title: "Don't show follow-up questions when the LLM asks one", est: 0.5, status: "not_started" },
  { sprint: "sep21", owner: "p-surya", goal: "revamp", title: "Set up an FAQ router in EverWiz chat in the new app", est: 1, status: "not_started" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Change the SOS deep-link notification logic (PR validation)", est: 0.5, status: "done", start: "2026-09-23", done: "2026-09-23" },
  { sprint: "sep21", owner: "p-kunal", goal: "revamp", title: "Weekly release", est: 0.5, status: "in_progress", start: "2026-09-25" },
  { sprint: "sep21", owner: "p-shreya", goal: "website", title: "Update non-tech blog content per QC remarks", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Add PostHog events for Vault and Journal", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Fix SOS poster sharing so the image loads", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Tooltip copy fixes from the Product team", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  {
    sprint: "sep21",
    owner: "p-aarthi",
    goal: "revamp",
    title: "Health Emergency UI fixes",
    notes: "Location font; Call CTA; missing call icon; EverWiz chat options shouldn't show until the keypad is open.",
    est: 0.5,
    status: "done",
    start: "2026-09-24",
    done: "2026-09-24",
  },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "SOS UI fixes: header, fonts and QR-to-text proportion", est: 1, status: "not_started" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Remove “-” from the LLM journal summary and UI fixes", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Day-opener follow-ups were hard-coded; made them dynamic", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "SOS “Review Poster Details”: photo required and age validation", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Health Emergency: enable and disable the call icon", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "“See previous messages” loads history above and keeps the scroll position", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "Make SOS Create Poster idempotent (tapping n times made n posters)", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Add exceptional PostHog events for Community and the permission screen", est: 0.5, status: "done", start: "2026-09-24", done: "2026-09-24" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Map reopens at the last saved location instead of the current location", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "SOS Last Seen address includes the street line", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Show the user's current location as a blue dot on the map", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-aarthi", goal: "revamp", title: "SOS: reject images that aren't of a dog", est: 1, status: "not_started" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Adjust the image into view by reusing the Community crop component", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-26" },
  { sprint: "sep21", owner: "p-shreya", goal: "revamp", title: "Export stored documents as PDF instead of BIN", est: 0.5, status: "in_progress", start: "2026-09-25" },
  { sprint: "sep21", owner: "p-vaishak", goal: "bowl", title: "Deploy the new bowl detection model on bowl 441 for testing", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
  { sprint: "sep21", owner: "p-pritam", goal: "revamp", title: "Scroll to top and bottom in long conversations", est: 0.5, status: "done", start: "2026-09-25", done: "2026-09-25" },
];
